### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by AlessandroMinervini** [eladcn/coronavirus_prediction#1]
Hi, 
but the two code rows:

`x = training_set[:, 0].reshape(-1, 1)
  y = training_set[:, 1]`

relate to the two column of this dataset? https://github.com/eladcn/coronavirus_prediction/blob/master/datasets/deaths_dataset_2020-03-15.csv

thanks

**Comment by eladcn** [comment]
Hey,
Yes, this code relates to both of the datasets (cases and deaths).
The x values are taken from the first column and y values are taken from the second column.
