### ISSUE TITLE
Not an issue but a question: How did you come up with the Cases and Death equations?

### ISSUE THREAD

**Issue by KiaraLicursi** [eladcn/coronavirus_prediction#2]
Not an issue but a question: How did you come up with the Cases and Death prediction equations?

Thank you and beautiful code!

Kiara

**Comment by eladcn** [comment]
Hey Kiara,

First of all - thank you for your kind words! I really appreciate that!

The equations for the cases and deaths models are the result of the polynomial regression process that we're doing in this code.
The aim of polynomial regression is to find a polynomial function of some degree that fits the data (i.e the coefficients of a polynomial function).
The code in this project takes the data from previous days (i.e cases and deaths in each day) and then fits a function to this data by running the polynomial regression algorithm using 'scikit-learn' library.
The result of this process is a model which contains the coefficients of the polynomial function that we fit to our data, and these coefficients can be used to express our polynomial function which is our equation.

I hope I explained it well enough :)

**Comment by KiaraLicursi** [comment]
Ah that's what I initially thought, great! thank you very much :) and thank you for creating this code!

Kiara

**Comment by eladcn** [comment]
You're welcome! I'm glad I could help!
